### PR TITLE
Include only existent files (no dirs) in config files discovery

### PR DESCRIPTION
**Pull request by jneira**
* To fix https://github.com/haskell/haskell-language-server/issues/417

### CODE REVIEW

**Comment by georgefst** [comment]
I'm not sure this is quite correct? Since that function is also used by e.g. `stackWorkDir`, which actually expects a directory.

**Comment by jneira** [comment]
@georgefst ugh, thanks for noting that, I saw the unused binding and I assumed with no further thinking that it should be used but we forgot to do it

**Comment by jneira** [comment]
Ok i think this veersion *could* be correct. It contains some duplication but i think names are clear. 
I've tested it with some projects and it worked fine. A test suite could be invaluable.

**Comment by jneira** [comment]
@Avi-D-coder dont want to be pushy but could you take a quick look to fix the bug asap?

**Review by Avi-D-coder — APPROVED** [review]
This looks correct.
I have not been able to test it.
If you think it's ready feel free to merge and I'll cut a release.

**Comment by Avi-D-coder** [comment]
I'm not exactly clear about how to reproduce https://github.com/haskell/haskell-language-server/issues/417, is it a standalone file or a project? What does `tree` look like?

**Comment by jneira** [comment]
i've reproduced it running hls in console mode in a directory with only a standalone hs and create in its parent directory an empty directory named .cabal

**Comment by Avi-D-coder** [comment]
Thanks. I have no concerns. I used hls with this patch and everything seems to work.

**Comment by jneira** [comment]
Yeah, it is ready. Thanks for testing it.

**Pull request merged**
