### PR TITLE
Adapt to lastest hie-bios breaking api changes

### PR DESCRIPTION
**Pull request by jneira**
//cc @Avi-D-coder @fendor

### CODE REVIEW

**Review by Avi-D-coder — APPROVED** [review]
Thanks for handling this

**Review by fendor — APPROVED** [review]
LGTM, thanks!

**Comment by Avi-D-coder** [comment]
@jneira Is this ready to merge?

**Comment by jneira** [comment]
@Avi-D-coder i think so, thanks for the invite!

**Pull request merged**
